# Settings ho an'ny Website
title: Bioacoustic Monitoring Framework
description: An end-to-end ecosystem from Edge to AI.
theme: jekyll-theme-minimal # Azonao ovaina ho: jekyll-theme-architect na jekyll-theme-cayman

# IZAY TENA ZAVA-DEHIBE:
# Ny baseurl dia tsy maintsy mitovy amin'ny anaran'ny repo-nao ao amin'ny GitHub
# Nataoko hoe /bioacoustic-monitoring satria izay no anaran'ilay repository ao amin'ny GitHub
baseurl: "/bioacoustic-monitoring" 
url: "https://milanto-hery.github.io"

# Mba hivoaka ny menu (miankina amin'ny theme)
header_pages:
  - index.md
  - docs/architecture.md
  - docs/acquisition.md
  - docs/labeling.md
  - docs/pipeline.md

# Mba ahafahan'ny Jekyll mamaky ny folder docs/
include: [docs, assets]
